version: '3'
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=your-database-host
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=your-database-name
      - DB_POSTGRESDB_USER=your-database-user
      - DB_POSTGRESDB_PASSWORD=your-database-password
    volumes:
      - ~/.n8n:/root/.n8n
